
package client.CAimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "centerServerService", targetNamespace = "http://server", wsdlLocation = "http://localhost:7777/CA?wsdl")
public class CenterServerService
    extends Service
{

    private final static URL CENTERSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CENTERSERVERSERVICE_EXCEPTION;
    private final static QName CENTERSERVERSERVICE_QNAME = new QName("http://server", "centerServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/CA?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTERSERVERSERVICE_WSDL_LOCATION = url;
        CENTERSERVERSERVICE_EXCEPTION = e;
    }

    public CenterServerService() {
        super(__getWsdlLocation(), CENTERSERVERSERVICE_QNAME);
    }

    public CenterServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTERSERVERSERVICE_QNAME, features);
    }

    public CenterServerService(URL wsdlLocation) {
        super(wsdlLocation, CENTERSERVERSERVICE_QNAME);
    }

    public CenterServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTERSERVERSERVICE_QNAME, features);
    }

    public CenterServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CenterServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CenterServerInterface
     */
    @WebEndpoint(name = "centerServerPort")
    public CenterServerInterface getCenterServerPort() {
        return super.getPort(new QName("http://server", "centerServerPort"), CenterServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CenterServerInterface
     */
    @WebEndpoint(name = "centerServerPort")
    public CenterServerInterface getCenterServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server", "centerServerPort"), CenterServerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTERSERVERSERVICE_EXCEPTION!= null) {
            throw CENTERSERVERSERVICE_EXCEPTION;
        }
        return CENTERSERVERSERVICE_WSDL_LOCATION;
    }

}
