package server.centerServerInterfaceIDL;


/**
* server/centerServerInterfaceIDL/CenterServerInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerInterfaceIDL.idl
* Friday, October 26, 2018 5:01:33 PM EDT
*/

abstract public class CenterServerInterfaceHelper
{
  private static String  _id = "IDL:server/centerServerInterfaceIDL/CenterServerInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, server.centerServerInterfaceIDL.CenterServerInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.centerServerInterfaceIDL.CenterServerInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (server.centerServerInterfaceIDL.CenterServerInterfaceHelper.id (), "CenterServerInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.centerServerInterfaceIDL.CenterServerInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CenterServerInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.centerServerInterfaceIDL.CenterServerInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static server.centerServerInterfaceIDL.CenterServerInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.centerServerInterfaceIDL.CenterServerInterface)
      return (server.centerServerInterfaceIDL.CenterServerInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server.centerServerInterfaceIDL._CenterServerInterfaceStub stub = new server.centerServerInterfaceIDL._CenterServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static server.centerServerInterfaceIDL.CenterServerInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.centerServerInterfaceIDL.CenterServerInterface)
      return (server.centerServerInterfaceIDL.CenterServerInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server.centerServerInterfaceIDL._CenterServerInterfaceStub stub = new server.centerServerInterfaceIDL._CenterServerInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
