package server.centerServerInterfaceIDL;


/**
* server/centerServerInterfaceIDL/CenterServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerInterfaceIDL.idl
* Friday, October 26, 2018 5:01:33 PM EDT
*/

public interface CenterServerInterface extends CenterServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServerInterface
