package server.centerServerInterfaceIDL;

/**
* server/centerServerInterfaceIDL/CenterServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerInterfaceIDL.idl
* Friday, October 26, 2018 5:01:33 PM EDT
*/

public final class CenterServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public server.centerServerInterfaceIDL.CenterServerInterface value = null;

  public CenterServerInterfaceHolder ()
  {
  }

  public CenterServerInterfaceHolder (server.centerServerInterfaceIDL.CenterServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.centerServerInterfaceIDL.CenterServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.centerServerInterfaceIDL.CenterServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.centerServerInterfaceIDL.CenterServerInterfaceHelper.type ();
  }

}
