package server.centerServerInterfaceIDL;


/**
* server/centerServerInterfaceIDL/ProjectInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerInterfaceIDL.idl
* Friday, October 26, 2018 5:01:33 PM EDT
*/

abstract public class ProjectInfoHelper
{
  private static String  _id = "IDL:server/centerServerInterfaceIDL/ProjectInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, server.centerServerInterfaceIDL.ProjectInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.centerServerInterfaceIDL.ProjectInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "projectId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "clientName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "projectName",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (server.centerServerInterfaceIDL.ProjectInfoHelper.id (), "ProjectInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.centerServerInterfaceIDL.ProjectInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    server.centerServerInterfaceIDL.ProjectInfo value = new server.centerServerInterfaceIDL.ProjectInfo ();
    value.projectId = istream.read_string ();
    value.clientName = istream.read_string ();
    value.projectName = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.centerServerInterfaceIDL.ProjectInfo value)
  {
    ostream.write_string (value.projectId);
    ostream.write_string (value.clientName);
    ostream.write_string (value.projectName);
  }

}
