package server.centerServerInterfaceIDL;

/**
* server/centerServerInterfaceIDL/ProjectInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServerInterfaceIDL.idl
* Friday, October 26, 2018 5:01:33 PM EDT
*/

public final class ProjectInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public server.centerServerInterfaceIDL.ProjectInfo value = null;

  public ProjectInfoHolder ()
  {
  }

  public ProjectInfoHolder (server.centerServerInterfaceIDL.ProjectInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.centerServerInterfaceIDL.ProjectInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.centerServerInterfaceIDL.ProjectInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.centerServerInterfaceIDL.ProjectInfoHelper.type ();
  }

}
